Phase4PizzaPortal/Models/ErrorViewModel.cs
using System;

namespace Phase4PizzaPortal.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Phase4PizzaPortal/Models/PizzaBO.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Phase4PizzaPortal.Models
{
    public class PizzaBO
    {
        public static List<PizzaModel> pizza;
        public PizzaBO()
        {
            pizza = new List<PizzaModel>
            {
                new PizzaModel{
                    PId = 1,
                    PName = "Margherita",
                    PCrustSize = "Small",
                    PDesc = "A hugely popular margherita, with a deliciously tangy single cheese topping",
                    PPrice = 75,
                    PImage = "https://i2.wp.com/www.vegrecipesofindia.com/wp-content/uploads/2020/12/margherita-pizza-4.jpg"
                },

                new PizzaModel{
                    PId = 2,
                    PName = "Double Cheese Margherita",
                    PCrustSize = "Medium",
                    PDesc = "The ever-popular margherita- loaded with extra cheese oodies of it",
                    PPrice = 110,
                    PImage = "https://tse1.mm.bing.net/th/id/OIP.HSuLEHkqf0pGEmsqLPdIDgHaKE?pid=ImgDet&rs=1"
                },

                new PizzaModel{
                    PId = 3,
                    PName = "Farm House",
                    PCrustSize = "Large",
                    PDesc = "A pizza that goes ballistic on veggies! check out this mouth watering overload of crunchy, crisp capsicum, succulent mushrooms and fresh tomatoes",
                    PPrice = 125,
                    PImage = "https://th.bing.com/th/id/R.6a2397dc47a5e64fa992efdba1629ff3?rik=dFfGlDvOSU5Gog&riu=http%3a%2f%2f3.bp.blogspot.com%2f-GEdhjxzjzVs%2fUpD3OFVvl8I%2fAAAAAAAAAQI%2fZlVGqNDCvIM%2fs1600%2fRecipe-of-farmhouse-pizza-food-factory.jpg&ehk=5AQn5%2f2%2bb1dDrmxojmUaA45iWzFJ%2bjo%2b4nE0yW86mlE%3d&risl=&pid=ImgRaw&r=0"
                },

                new PizzaModel{
                    PId = 4,
                    PName = "Peppy Paneer",
                    PCrustSize = "Extra Large",
                    PDesc = "Chunky paneer with crisp capsisum and spicy red pepper- quite a mouthful!",
                    PPrice = 175,
                    PImage = "https://s3-eu-west-1.amazonaws.com/cdn.nordic-wewalka/ww-pizza_spinat_1742.jpg"
                },

                new PizzaModel{
                    PId = 5,
                    PName = "Mexican GreenWave",
                    PCrustSize = "Extra Large",
                    PDesc = "A pizza loaded with crunchy onions, crisp capsicums, juicy tomatoes and jalapeno with a liberal sprinkling of exotic mexican herbs",
                    PPrice = 175,
                    PImage = "https://cdn.shopify.com/s/files/1/0808/5563/products/061219_Pepperoni_Full_1200x1200.jpg?v=1560820716"
                },

                new PizzaModel{
                    PId = 6,
                    PName = "Delux Veggie",
                    PCrustSize = "Large",
                    PDesc = "For a vegetarian looking for a big treat that goes easy on spices, this one's goes it all. The onions, the capsicum, those delectable mushrooms- with paneer and golden corn to top it all",
                    PPrice = 135,
                    PImage = "https://tse1.mm.bing.net/th/id/OIP.Mu_qclDo5gWcrPcId1m_IwHaHa?pid=ImgDet&rs=1"
                },

                new PizzaModel{
                    PId = 7,
                    PName = "Veg Extravaganza",
                    PCrustSize = "Medium",
                    PDesc = "A pizza that decidedly straggers under an overload of golden corn, exotic black olives, crunchy onions, crisp capsicum, succulent mushrooms, juicy fresh tomatoes and jalapeno- with extra cheese to go all around",
                    PPrice = 110,
                    PImage = "https://tse1.mm.bing.net/th/id/OIP.f4KsUS1N-qtIPyB6NS3L5QHaEo?pid=ImgDet&rs=1"
                },

                new PizzaModel{
                    PId = 8,
                    PName = "Cheese n corn",
                    PCrustSize = "Small",
                    PDesc = "Cheese I golden corn",
                    PPrice = 90,
                    PImage = "https://tse4.mm.bing.net/th/id/OIP.D3HFxRIoiAPr8oE0sc_AbAHaHa?pid=ImgDet&rs=1"
                }

            };
        }

        public List<PizzaModel> GetAllPizzas()
        {
            return pizza;
        }

        public PizzaModel GetPizzaById(int id)
        {
            return pizza.Find(p => p.PId == id);
        }
    }
}

Phase4PizzaPortal/Models/PizzaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Phase4PizzaPortal.Models
{
    public class PizzaModel
    {
        public int PId { get; set; }
        public string PName { get; set; }
        public string PCrustSize { get; set; }
        public string PDesc { get; set; }
        public decimal PPrice { get; set; }
        public string PImage { get; set; }
    }
}

Phase4PizzaPortal/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Phase4PizzaPortal.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Phase4PizzaPortal.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Phase4PizzaPortal/Controllers/PizzaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Phase4PizzaPortal.Models;

namespace Phase4PizzaPortal.Controllers
{
    public class PizzaController : Controller
    {
        private static readonly PizzaBO _context = new PizzaBO();

        public IActionResult Index()
        {
            return View(_context.GetAllPizzas());
        }

        public IActionResult Details(int id)
        {
            return View(_context.GetPizzaById(id));
        }

        public IActionResult Order(int id)
        {
            ViewBag.name = _context.GetPizzaById(id).PName;
            ViewBag.price = _context.GetPizzaById(id).PPrice;
            ViewBag.total = _context.GetPizzaById(id).PPrice;
            return View();
        }

        public IActionResult status()
        {
            return View();
        }

    }
}

Phase4PizzaPortal/Views/Home/Index.cshtml
<style>
    .container-fluid {
        background-image: url('images/home.jpg');
        background-repeat: no-repeat;
        background-size: cover;
        background-attachment: fixed;
        height: 600px;
    }

    #head1, #head2{
        color:white;
        font-family:'Times New Roman', Times, serif;
    }

    #head1{
        padding-top:2rem;
    }

</style>

<body>
    <div class="container-fluid text-center">
        <h1 id="head1">Welcome to Pizza Portal</h1>
        <h4 id="head2">Order your pizza, enjoy every bite...!</h4>
    </div>
</body>

Phase4PizzaPortal/Views/Pizza/Details.cshtml
@model Phase4PizzaPortal.Models.PizzaModel

@{
    ViewData["Title"] = "Details";
}

<h1 class="container">Details</h1>

<div class="container">
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Name:
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PName)
        </dd>
        <dt class="col-sm-2">
            Crust Size
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PCrustSize)
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PDesc)
        </dd>
        <dt class="col-sm-2">
            Price
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PPrice)
        </dd>
        <dt class="col-sm-2">
            Image
        </dt>
        <dd class="col-sm-10">
            <img src="@Model.PImage" alt="Pizza Image" height="200" />
        </dd>
    </dl>
</div>
<div class="container">
    <a id="back" asp-action="Index">Back to List</a>
</div>

Phase4PizzaPortal/Views/Pizza/Index.cshtml
@model IEnumerable<Phase4PizzaPortal.Models.PizzaModel>

@{
    ViewData["Title"] = "Index";
}

<html>

<head>

    <style>

        #top {
            background-color: #8E05C2;
        }

        #heading1 {
            padding-top: 2rem;
            color: white;
            font-family: Cambria, Cochin, Georgia, Times, Times New Roman, serif;
        }

        #heading2 {
            padding-top: .5rem;
            color: white;
            font-family: 'Agency FB';
            padding-bottom: 2rem;
        }

        #cartSection {
            margin-top: 1rem;
            margin-bottom: 1rem;
        }


        #pizza {
            margin-top: 2rem;
            margin-bottom: 5rem;
        }

        #pizzaItems {
            margin-top: 1rem;
        }
    </style>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>

<body>
    <div id="top" class="container">
        <h3 id="heading1">Hello, it is our pleasure to have you as Customer...!</h3>
        <h5 id="heading2">Enjoy your pizza by ordering</h5>
    </div>

    <div id="pizza" class="container">
        <div class="row">
            @foreach (var item in Model)
            {
                <div id="pizzaItems" class="col-lg-3 col-md-6 col-sm-12">
                    <div class="card shadow-sm">
                        <img class="card-img-top" src="@item.PImage" alt="Pizza Image" height="200" /><hr />

                        <div class="card-body" style="height:200px">
                            <h4 style="font-family:'Times New Roman', Times, serif">@Html.DisplayFor(modelItem => item.PName)</h4>

                            <p class="text-muted">Crust Size: @item.PCrustSize </p>

                            <p class="card-text" style="font-family:'Times New Roman', Times, serif">
                                @if (item.PDesc.Length > 50)
                                {
                                    @(item.PDesc.Substring(0,49) + "..." )
                                }
                                else
                                {
                                    @Html.DisplayFor(modelItem => item.PDesc)
                                }
                            </p>

                            <div class=" justify-content-between align-items-center">
                                <div class="btn-group">
                                    <a id="@item.PId" class="btn btn-sm btn-primary" onclick="javacript:DisplayMessage()" asp-action="Order" asp-route-id="@item.PId">Order Pizza</a>
                                </div>
                                <small class="text-muted" style="float:right"> @Html.DisplayFor(modelItem => item.PPrice) rs</small>
                            </div>

                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</body>

</html>

Phase4PizzaPortal/Views/Pizza/Order.cshtml
@model Phase4PizzaPortal.Models.PizzaModel

@{
    ViewData["Title"] = "Order";
}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Checkout example · Bootstrap v5.1</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/checkout/">

    <!-- Bootstrap core CSS -->
    <link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
    <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#7952b3">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        .sections {
            padding-bottom: 8rem;
        }
    </style>

    <!-- Custom styles for this template -->
    <link href="form-validation.css" rel="stylesheet">
</head>

<body class="bg-light">
    <div class="container sections">
        <main>
            <div class="py-5 text-center">
                <h2>Bill & Billing Details</h2>
            </div>

            <div class="row g-5">
                <div class="col-md-5 col-lg-4 order-md-last">
                    <h4 class="d-flex justify-content-between align-items-center mb-3">
                        <span class="text-primary">Your Pizzas</span>
                        <span class="badge bg-primary rounded-pill">1</span>
                    </h4>
                    <ul class="list-group mb-3">
                        <li class="list-group-item d-flex justify-content-between lh-sm">
                            <div>
                                <h6 class="my-0">@ViewBag.name</h6>
                                <small class="text-muted">Qty: 1</small>
                            </div>
                            <span class="text-muted">@ViewBag.price</span>
                        </li>
                    </ul>
                    <ul class="list-group mb-3">
                        <li class="list-group-item d-flex justify-content-between">
                            <span>Total (Rs)</span>
                            <strong>@ViewBag.total</strong>
                        </li>
                    </ul>
                </div>

                <div class="col-md-7 col-lg-8">
                    <h4 class="mb-3">Billing address</h4>
                    <form class="needs-validation" novalidate>
                        <div class="row g-3">
                            <div class="col-sm-6">
                                <label for="firstName" class="form-label">First name</label>
                                <input id="fn" type="text" class="form-control" id="firstName" placeholder="" value="" required>
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <label for="lastName" class="form-label">Last name</label>
                                <input id="ln" type="text" class="form-control" id="lastName" placeholder="" value="" required>
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="email" class="form-label">Email</label>
                                <input id="email" type="email" class="form-control" id="email" placeholder="you@example.com" required>
                                <div class="invalid-feedback">
                                    Please enter a valid email address for shipping updates.
                                </div>
                            </div>

                            <div class="col-12">
                                <label for="address" class="form-label">Address</label>
                                <input id="add" type="text" class="form-control" id="address" placeholder="1234 Main St" required>
                                <div class="invalid-feedback">
                                    Please enter your shipping address.
                                </div>
                            </div>

                            <div class="col-md-3">
                                <label for="zip" class="form-label">ZipCode</label>
                                <input id="zip" type="text" class="form-control" id="zip" placeholder="" required>
                                <div class="invalid-feedback">
                                    Zip code required.
                                </div>
                            </div>
                        </div>

                        <hr class="my-4" />

                        <h4 class="mb-3">Payment</h4>

                        <div class="my-3">
                            <div class="form-check">
                                <input id="cash" value="1" id="cash" name="paymentMethod" type="radio" class="form-check-input" onClick="displayForm(this)" required>
                                <label class="form-check-label" for="cash" onclick="">Cash on Delivery</label>
                            </div>
                            <div class="form-check">
                                <input id="credit" value="2" id="credit" name="paymentMethod" type="radio" class="form-check-input" onClick="displayForm(this)" required>
                                <label class="form-check-label" for="credit">Credit card</label>
                            </div>
                            <div class="form-check">
                                <input id="debit" value="3" id="debit" name="paymentMethod" type="radio" class="form-check-input" onClick="displayForm(this)" required>
                                <label class="form-check-label" for="debit">Debit card</label>
                            </div>
                            <div class="form-check">
                                <input id="paypal" value="4" id="paypal" name="paymentMethod" type="radio" class="form-check-input" onClick="displayForm(this)" required>
                                <label class="form-check-label" for="paypal">PayPal</label>
                            </div>
                        </div>

                        <hr class="my-4">

                        <button id="checkout" class="w-100 btn btn-primary btn-lg but" type="submit" asp-action="status">Continue to checkout</button>
                    </form>
                </div>
            </div>
        </main>
    </div>

    <script src="/docs/5.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <script src="form-validation.js"></script>
</body>
</html>

Phase4PizzaPortal/Views/Pizza/status.cshtml
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


<div class="px-4 py-5 my-5 text-center">
    <h1 class="display-5 fw-bold">Success Status</h1>
    <div class="col-lg-6 mx-auto">
        <p class="lead mb-4">Congratulations...! Your order is successfully placed and you will recieve your order very soon. Enjoy your pizza....!</p>
        <h5>Thank you for your orders..Please visit again</h5>
        <br /><br />
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <a id="again" type="button" class="btn btn-primary btn-lg px-4 gap-3" asp-controller="Pizza" asp-action="Index">Order again</a>
            <a type="button" class="btn btn-outline-secondary btn-lg px-4" asp-controller="Home" asp-action="Index">Exit to Home</a>
        </div>
    </div>
</div>

Phase4PizzaPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Phase4PizzaPortal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Pizza Portal</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Shop Pizza</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Phase4PizzaPortal - RamyaKT
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>